spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:compose}
    group:
      dev: db_local, msg_local, loggiing_local
      compose: db_docker, msg_docker
      custom: db_local, msg_docker
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

logging:
  pattern:
    level: "%5p [%X{traceId:-}]"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
